### ISSUE TITLE
Repo maintenance and future development

### ISSUE THREAD

**Issue by Marcondiro** [sum-catnip/libipt-rs#6]
Hi @sum-catnip

Thanks for all the work you've put into this project.
I wanted to check if the project is still being maintained and if you're open to pull requests for updates or new features.

If not, would you suggest forking it to publish a version 2?

Appreciate your time and everything you’ve done with this project.

Best,
Marco

**Comment by sum-catnip** [comment]
Hey, thank you for the kind words :)

At some point i came to the conclusion that it made more sense to write a custom parser instead of relying on the libipt reference implementation, especially if you only need a subset of the packets. Youre very much free to fork it or continue making pull requests. Id even be willing to hand over the cargo package name if thats even possible :p

**Comment by Marcondiro** [comment]
I'm glad to hear you're open to PRs!
If you wish (and you trust me 😁) feel free to add me to the owners of the crates on crates.io, it would be awesome continuing with the same name.

**Comment by sum-catnip** [comment]
you seem quite trustworthy judging by your commits on other repos :p
would you mind having a quick chat on another platform? im open for any messenger ^^
